name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_DIR: app/test/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Flake8
        run: python3 -m flake8 app
      - name: Run Pytest
        working-directory: ./${{ env.TEST_DIR }}
        run: |
          python -m pytest -v
      - name: Generate coverage file
        run: |
          pytest --cache-clear --cov=app ./${{ env.TEST_DIR }} > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2